Working with the data

In [1]:
import pandas as pd
import json
import numpy as np
from bs4 import BeautifulSoup
import math
import os

In [2]:
def remove_tags(html):
    soup = BeautifulSoup(html, "html.parser")

    # Find and replace <img> tags with their 'alt' attribute
    for img in soup.find_all('img'):
        alt_text = img.get('alt', '')  # default to empty string if 'alt' is None
        if alt_text:
            # Create a new text node
            new_text = soup.new_string(" " + alt_text + " ")
            img.replace_with(new_text)
        else:
            # Remove the image if no alt text
            img.decompose()

    # Remove all script and style elements
    for tag in soup(['script', 'style']):
        tag.decompose()

    # Extract the text, cleaning up any excessive whitespace
    clean_text = ' '.join(soup.stripped_strings)
    return clean_text

In [3]:

dataset_paths = ['assist2009/skill_builder_data_corrected_collapsed.csv', 
 'assist2012/2012-2013-data-with-predictions-4-final.csv', 
 'assist2017/anonymized_full_release_competition_dataset.csv']
datasets = ['assist2009', 'assist2012', 'assist2017']

pb_df = pd.read_csv('./data_subsets/ProblemBodies_23.csv', low_memory=False)

In [4]:
dataset_paths[0] , datasets[0]

('assist2009/skill_builder_data_corrected_collapsed.csv', 'assist2009')

In [6]:
pb_df.head()

,problem_id,problem_code,assistment_id,problem_set_id,problem_set_type,problem_set_name,curriculum,grade_or_subject,unit,link,...,attempts,correct_count,percent_correct,first_cwa,first_cwa_count,second_cwa,second_cwa_count,third_cwa,third_cwa_count,answer
0,1152985.0,PRA5FZU,780070.0,PSAQKFU,NaN,"8.5 Comparing Linear, Exponential, and Quadrat...",Textbook Curricula,Big Ideas Learning,HS: Purple Algebra I (2014),https://app.assistments.org/find/lv/lesson/328...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Exponential
1,1164390.0,PRA5S4J,789764.0,PSAUDWH,NaN,Variables and Patterns Investigation 1 ACE,Textbook Curricula,Pearson (Prentice-Hall),CMP 3,https://app.assistments.org/find/lv/lesson/329...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1167935.0,PRA5V8Q,792776.0,PSAUK4X,NaN,Variables and Patterns Investigation 3 ACE,Textbook Curricula,Pearson (Prentice-Hall),CMP 3,https://app.assistments.org/find/lv/lesson/329...,...,33.0,21.0,63.6,18,3.0,15,2.0,0.3,1.0,12
3,1152694.0,PRA5FRU,779822.0,PSATNY9,NaN,9.7 Independent and Dependent Events,Textbook Curricula,Glencoe McGraw-Hill,Grade 7: Course 2 (2015),https://app.assistments.org/find/lv/lesson/328...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
4,1217278.0,PRA6768,832131.0,PSAVWDT,NaN,Covering and Surrounding ACE Investigation 4,Textbook Curricula,Pearson (Prentice-Hall),CMP 3,https://app.assistments.org/find/lv/lesson/329...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,32

In [7]:
print(pb_df.columns)

Index(['problem_id', 'problem_code', 'assistment_id', 'problem_set_id',
       'problem_set_type', 'problem_set_name', 'curriculum',
       'grade_or_subject', 'unit', 'link', 'skill_codes', 'skill_names',
       'problem_type', 'problem_body', 'attempts', 'correct_count',
       'percent_correct', 'first_cwa', 'first_cwa_count', 'second_cwa',
       'second_cwa_count', 'third_cwa', 'third_cwa_count', 'answer'],
      dtype='object')

In [23]:
pb_df['assistment_id'][1997:2025],pb_df['problem_set_id'][1997:2025]

(1997    1167675.0
 1998     805977.0
 1999    1164522.0
 2000    1164587.0
 2001     806008.0
 2002     806032.0
 2003    1164531.0
 2004     806038.0
 2005     806039.0
 2006     805994.0
 2007     806027.0
 2008    1164529.0
 2009    1164577.0
 2010    1164534.0
 2011    1164630.0
 2012    1164632.0
 2013     783041.0
 2014     783637.0
 2015    1167684.0
 2016    1164540.0
 2017     782672.0
 2018     782670.0
 2019     782657.0
 2020     782673.0
 2021    1164788.0
 2022     783677.0
 2023     887800.0
 2024    1135972.0
 Name: assistment_id, dtype: float64,
 1997    PSABAG8U
 1998     PSAVHVW
 1999    PSABACAA
 2000    PSABACR3
 2001     PSAVHVW
 2002     PSAVHVW
 2003    PSABACAA
 2004     PSAVHVW
 2005     PSAVHVW
 2006     PSAVHVW
 2007     PSAVHVW
 2008    PSABACAA
 2009    PSABACSM
 2010    PSABACAA
 2011    PSABACSM
 2012    PSABACSM
 2013     PSATV76
 2014     PSATX8Q
 2015    PSABAG82
 2016    PSABACR3
 2017     PSATVYP
 2018     PSATVYP
 2019     PSATVPA
 2020     PSATVYP
 2021    PSABAA6N
 2022     PSATYAZ
 2023     PSAXUXM
 2024     PSA9KU2
 Name: problem_set_id, dtype: object)

In [24]:
pb_df['problem_set_type'][1997:2025],pb_df['problem_set_name'][1997:2025]

(1997    NaN
 1998    NaN
 1999    NaN
 2000    NaN
 2001    NaN
 2002    NaN
 2003    NaN
 2004    NaN
 2005    NaN
 2006    NaN
 2007    NaN
 2008    NaN
 2009    NaN
 2010    NaN
 2011    NaN
 2012    NaN
 2013    NaN
 2014    NaN
 2015    NaN
 2016    NaN
 2017    NaN
 2018    NaN
 2019    NaN
 2020    NaN
 2021    NaN
 2022    NaN
 2023    NaN
 2024    NaN
 Name: problem_set_type, dtype: object,
 1997                    Lesson 9 Preparing for Assessment
 1998                       Prime Time Investigation 3 ACE
 1999    6-2 Solving Systems Using Substitution: Key Co...
 2000                           Chapter 8 Mid-Chapter Quiz
 2001                       Prime Time Investigation 3 ACE
 2002                       Prime Time Investigation 3 ACE
 2003    6-2 Solving Systems Using Substitution: Key Co...
 2004                       Prime Time Investigation 3 ACE
 2005                       Prime Time Investigation 3 ACE
 2006                       Prime Time Investigation 3 ACE
 2007                       Prime Time Investigation 3 ACE
 2008    6-2 Solving Systems Using Substitution: Key Co...
 2009    Lesson 11.1 - Cross Sections and Solids of Rev...
 2010    6-2 Solving Systems Using Substitution: Key Co...
 2011    Lesson 11.1 - Cross Sections and Solids of Rev...
 2012    Lesson 11.1 - Cross Sections and Solids of Rev...
 2013               Problem 1.3 The Community Pool Problem
 2014    Problem 2.3 Solving Systems by Combining Equat...
 2015                 Lesson 12-8 Two-Way Frequency Tables
 2016                           Chapter 8 Mid-Chapter Quiz
 2017         Problem 4.4 Getting Real: Irrational Numbers
 2018         Problem 4.4 Getting Real: Irrational Numbers
 2019       Problem 4.3 Representing Decimals as Fractions
 2020         Problem 4.4 Getting Real: Irrational Numbers
 2021        10.2 - Areas of Trapazoid, Rhombi, and Kites
 2022    Problem 3.1 Comparing Security Services: Linea...
 2023    5.2 Adding and Subtracting with Unlike Denomin...
 2024    1-9 Patterns equations and Graphs: Key Concept...
 Name: problem_set_name, dtype: object)

In [5]:
dataset = datasets[0]
dataset_path = dataset_paths[0]

In [25]:
assist_df = pd.read_csv('raw_data/' + dataset_path, encoding = "ISO-8859-1", low_memory=False)
problem_id_column_name = 'problem_id'

In [26]:
assist_df.head()

,Unnamed: 0,order_id,assignment_id,user_id,assistment_id,problem_id,original,correct,attempt_count,ms_first_response,...,hint_count,hint_total,overlap_time,template_id,answer_id,answer_text,first_action,bottom_hint,opportunity,opportunity_original
0,1,33022537,277618,64525,33139,51424,1,1,1,32454,...,0,3,32454,30799,NaN,26,0,NaN,1,1.0
1,2,33022709,277618,64525,33150,51435,1,1,1,4922,...,0,3,4922,30799,NaN,55,0,NaN,2,2.0
2,3,35450204,220674,70363,33159,51444,1,0,2,25390,...,0,3,42000,30799,NaN,88,0,NaN,1,1.0
3,4,35450295,220674,70363,33110,51395,1,1,1,4859,...,0,3,4859,30059,NaN,41,0,NaN,2,2.0
4,5,35450311,220674,70363,33196,51481,1,0,14,19813,...,3,4,124564,30060,NaN,65,0,0.0,3,3.0

In [29]:
len(assist_df)

346860

In [27]:
questions = assist_df[problem_id_column_name].unique()
questions_w_text = pb_df[pb_df['problem_id'].isin(questions)]

In [30]:
len(questions)

26688

In [31]:
questions_w_text

,problem_id,problem_code,assistment_id,problem_set_id,problem_set_type,problem_set_name,curriculum,grade_or_subject,unit,link,...,attempts,correct_count,percent_correct,first_cwa,first_cwa_count,second_cwa,second_cwa_count,third_cwa,third_cwa_count,answer
2190,119299.0,PRACDD6,62585.0,PSAJ78,NaN,(7.SP.C.7a) Probability of a Single Event Skil...,Skill Builders,Grade 7,(SP) Statistics and Probability,https://app.assistments.org/find/lv/lesson/328...,...,61.0,20.0,32.8,"<img style=""width: 237px; height: 53px;"" src=""...",10.0,"<img style=""width: 204px; height: 22px;"" src=""...",9.0,"<img style=""width: 237px; height: 22px;"" src=""...",8.0,"<img style=""width: 246px; height: 57px;"" src=""..."
2654,97581.0,PRAB54Z,55574.0,PSAGGT,NaN,(7.EE.B.4a) Solving Equations (with Combining ...,Skill Builders,Grade 7,(EE) Expressions and Equations,https://app.assistments.org/find/lv/lesson/328...,...,56.0,26.0,46.4,B),12.0,D),8.0,A),8.0,C)
2930,79936.0,PRABSBM,44247.0,PSAGZU,NaN,(8.G.B.7) Pythagorean Theorem - Finding a Miss...,Skill Builders,Grade 8,(G) Geometry,https://app.assistments.org/find/lv/lesson/328...,...,62.0,28.0,45.2,the sum of the two other sides.,13.0,half the base times the height.,8.0,the square of one of the sides.,6.0,the sum of the squares of the two other sides.
2933,76339.0,PRABQWX,42893.0,PSANGJ,NaN,(6.G.A.1) Area of a Trapezoid Skill Builder,Skill Builders,Grade 6,(G) Geometry,https://app.assistments.org/find/lv/lesson/328...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,45
2941,89068.0,PRABYHY,50210.0,PSAHSU,NaN,(8.G.A.5) Sum of Interior Angles of Triangles ...,Skill Builders,Grade 8,(G) Geometry,https://app.assistments.org/find/lv/lesson/328...,...,52.0,30.0,57.7,135,3.0,180,2.0,1440,2.0,1080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
472553,90055.0,PRABZE7,51085.0,PSAHKR,NaN,(7.NS.A.2c) Dividing Integers Skill Builder,Skill Builders,Grade 7,(NS) The Number System,https://app.assistments.org/find/lv/lesson/328...,...,226.0,160.0,70.8,0,18.0,-100,5.0,-10,5.0,-1
472614,90238.0,PRABZJ2,51204.0,PSAHKR,NaN,(7.NS.A.2c) Dividing Integers Skill Builder,Skill Builders,Grade 7,(NS) The Number System,https://app.assistments.org/find/lv/lesson/328...,...,305.0,253.0,83.0,-1,17.0,-2,5.0,1,5.0,-3
472619,90230.0,PRABZJS,51196.0,PSAHKR,NaN,(7.NS.A.2c) Dividing Integers Skill Builder,Skill Builders,Grade 7,(NS) The Number System,https://app.assistments.org/find/lv/lesson/328...,...,203.0,178.0,87.7,-9,2.0,-5,2.0,5,1.0,-6
472622,90174.0,PRABZGY,51140.0,PSAHKR,NaN,(7.NS.A.2c) Dividing Integers Skill Builder,Skill Builders,Grade 7,(NS) The Number System,https://app.assistments.org/find/lv/lesson/328...,...,227.0,179.0,78.9,-3,25.0,27,7.0,1,2.0,3
472639,89971.0,PRABZEA,51057.0,PSAHKR,NaN,(7.NS.A.2c) Dividing Integers Skill Builder,Skill Builders,Grade 7,(NS) The Number System,https://app.assistments.org/find/lv/lesson/328...,...,278.0,230.0,82.7,-8,4.0,-1,2.0,8,2.0,-2

In [32]:
len(questions_w_text)

7942

In [33]:
print(f'Number of total questions in {dataset} : {len(questions)}')
print(f'Number of questions in {dataset} with text: {len(questions_w_text)}')

Number of total questions in assist2009 : 26688
Number of questions in assist2009 with text: 7942

In [35]:
assist_df_temp = assist_df[assist_df[problem_id_column_name].isin(questions_w_text['problem_id'])]
assist_df_temp.to_csv('../data/' + dataset_path)

In [36]:
with open('../data/'+ dataset + '/keyid2idx.json', 'r') as f:
        keyid2idx_pb_subset = json.load(f)
print(f'Loaded keyid2idx_pb_subset for {dataset}')

Loaded keyid2idx_pb_subset for assist2009

In [37]:
keyid2idx_pb_subset

{'questions': {'54003': 0,
  '53991': 1,
  '54071': 2,
  '54015': 3,
  '53987': 4,
  '53781': 5,
  '54193': 6,
  '53795': 7,
  '54130': 8,
  '54035': 9,
  '49276': 10,
  '53966': 11,
  '54593': 12,
  '90498': 13,
  '89863': 14,
  '89737': 15,
  '60011': 16,
  '71776': 17,
  '90210': 18,
  '54051': 19,
  '53317': 20,
  '53008': 21,
  '54456': 22,
  '66825': 23,
  '66826': 24,
  '66827': 25,
  '51186': 26,
  '66813': 27,
  '84817': 28,
  '53609': 29,
  '53999': 30,
  '86549': 31,
  '53786': 32,
  '49286': 33,
  '49270': 34,
  '49290': 35,
  '49265': 36,
  '49278': 37,
  '85714': 38,
  '84951': 39,
  '84724': 40,
  '84938': 41,
  '84974': 42,
  '84788': 43,
  '85826': 44,
  '86054': 45,
  '61100': 46,
  '87777': 47,
  '86102': 48,
  '88521': 49,
  '87045': 50,
  '54460': 51,
  '54612': 52,
  '58775': 53,
  '60111': 54,
  '109008': 55,
  '108966': 56,
  '108924': 57,
  '109011': 58,
  '108957': 59,
  '87560': 60,
  '87461': 61,
  '87597': 62,
  '87471': 63,
  '87538': 64,
  '87590': 65,
  '87563': 66,
  '87512': 67,
  '87517': 68,
  '87425': 69,
  '89706': 70,
  '90237': 71,
  '90639': 72,
  '89953': 73,
  '86200': 74,
  '86188': 75,
  '86157': 76,
  '86160': 77,
  '54124': 78,
  '86895': 79,
  '54298': 80,
  '66079': 81,
  '52813': 82,
  '66545': 83,
  '97836': 84,
  '97884': 85,
  '97788': 86,
  '97828': 87,
  '97824': 88,
  '66187': 89,
  '53327': 90,
  '66699': 91,
  '78930': 92,
  '78902': 93,
  '79063': 94,
  '79056': 95,
  '78866': 96,
  '79004': 97,
  '79072': 98,
  '84605': 99,
  '51156': 100,
  '50990': 101,
  '51044': 102,
  '80882': 103,
  '80714': 104,
  '80738': 105,
  '80862': 106,
  '80902': 107,
  '80878': 108,
  '80686': 109,
  '71352': 110,
  '87966': 111,
  '71385': 112,
  '58724': 113,
  '58693': 114,
  '58689': 115,
  '88430': 116,
  '86367': 117,
  '85593': 118,
  '128665': 119,
  '85625': 120,
  '85582': 121,
  '85586': 122,
  '87267': 123,
  '87315': 124,
  '87311': 125,
  '87341': 126,
  '87349': 127,
  '88284': 128,
  '86641': 129,
  '86635': 130,
  '86712': 131,
  '86709': 132,
  '86938': 133,
  '92320': 134,
  '94868': 135,
  '92335': 136,
  '84671': 137,
  '84677': 138,
  '85216': 139,
  '85061': 140,
  '89682': 141,
  '80514': 142,
  '80406': 143,
  '80628': 144,
  '80640': 145,
  '80340': 146,
  '80568': 147,
  '80544': 148,
  '80478': 149,
  '80442': 150,
  '86759': 151,
  '53863': 152,
  '87154': 153,
  '61679': 154,
  '87462': 155,
  '87450': 156,
  '87567': 157,
  '87596': 158,
  '87460': 159,
  '87601': 160,
  '78863': 161,
  '79042': 162,
  '79040': 163,
  '79039': 164,
  '79031': 165,
  '78884': 166,
  '78881': 167,
  '79022': 168,
  '87468': 169,
  '85366': 170,
  '53553': 171,
  '89746': 172,
  '86330': 173,
  '58807': 174,
  '49274': 175,
  '49264': 176,
  '49261': 177,
  '49281': 178,
  '85707': 179,
  '84838': 180,
  '84722': 181,
  '84930': 182,
  '85849': 183,
  '85934': 184,
  '61101': 185,
  '61095': 186,
  '61099': 187,
  '61098': 188,
  '87677': 189,
  '86118': 190,
  '88624': 191,
  '87128': 192,
  '54454': 193,
  '54526': 194,
  '58797': 195,
  '60071': 196,
  '108942': 197,
  '108999': 198,
  '108963': 199,
  '108990': 200,
  '108939': 201,
  '108978': 202,
  '87443': 203,
  '87540': 204,
  '87520': 205,
  '87589': 206,
  '87537': 207,
  '87428': 208,
  '87585': 209,
  '87599': 210,
  '90179': 211,
  '90531': 212,
  '89923': 213,
  '86203': 214,
  '86227': 215,
  '86143': 216,
  '86173': 217,
  '86163': 218,
  '86149': 219,
  '54104': 220,
  '86778': 221,
  '62598': 222,
  '53017': 223,
  '66543': 224,
  '97864': 225,
  '97868': 226,
  '97896': 227,
  '97912': 228,
  '65681': 229,
  '53304': 230,
  '66609': 231,
  '78969': 232,
  '78943': 233,
  '78947': 234,
  '79013': 235,
  '79066': 236,
  '85110': 237,
  '66864': 238,
  '50995': 239,
  '51032': 240,
  '80870': 241,
  '80818': 242,
  '80718': 243,
  '80706': 244,
  '80670': 245,
  '80734': 246,
  '80682': 247,
  '71347': 248,
  '88082': 249,
  '88075': 250,
  '91466': 251,
  '88070': 252,
  '88087': 253,
  '88066': 254,
  '71390': 255,
  '58669': 256,
  '58725': 257,
  '58717': 258,
  '88493': 259,
  '86247': 260,
  '86370': 261,
  '86241': 262,
  '86239': 263,
  '128661': 264,
  '128643': 265,
  '128668': 266,
  '85600': 267,
  '85588': 268,
  '87552': 269,
  '87532': 270,
  '87594': 271,
  '87583': 272,
  '87536': 273,
  '78974': 274,
  '79008': 275,
  '78859': 276,
  '79032': 277,
  '79065': 278,
  '79012': 279,
  '78988': 280,
  '79015': 281,
  '78903': 282,
  '80890': 283,
  '87356': 284,
  '87362': 285,
  '87321': 286,
  '87317': 287,
  '87286': 288,
  '88208': 289,
  '86582': 290,
  '86941': 291,
  '94900': 292,
  '85015': 293,
  '92327': 294,
  '89608': 295,
  '80454': 296,
  '80526': 297,
  '80388': 298,
  '80316': 299,
  '80490': 300,
  '80376': 301,
  '80610': 302,
  '86666': 303,
  '53880': 304,
  '87244': 305,
  '61619': 306,
  '61694': 307,
  '61448': 308,
  '61625': 309,
  '88963': 310,
  '71777': 311,
  '75281': 312,
  '79115': 313,
  '79140': 314,
  '79177': 315,
  '79148': 316,
  '79181': 317,
  '79104': 318,
  '79141': 319,
  '75245': 320,
  '79207': 321,
  '79232': 322,
  '79243': 323,
  '79237': 324,
  '79203': 325,
  '79248': 326,
  '79244': 327,
  '75269': 328,
  '79374': 329,
  '79560': 330,
  '79842': 331,
  '81169': 332,
  '80047': 333,
  '80042': 334,
  '80044': 335,
  '80018': 336,
  '80015': 337,
  '81204': 338,
  '80070': 339,
  '80196': 340,
  '80200': 341,
  '75033': 342,
  '80283': 343,
  '80291': 344,
  '80280': 345,
  '80301': 346,
  '71677': 347,
  '86485': 348,
  '86490': 349,
  '94999': 350,
  '86497': 351,
  '86559': 352,
  '86468': 353,
  '74793': 354,
  '89175': 355,
  '93017': 356,
  '93005': 357,
  '92969': 358,
  '92987': 359,
  '79159': 360,
  '79240': 361,
  '79003': 362,
  '51424': 363,
  '51435': 364,
  '93432': 365,
  '93447': 366,
  '93448': 367,
  '93429': 368,
  '57689': 369,
  '58584': 370,
  '57698': 371,
  '58542': 372,
  '47117': 373,
  '47090': 374,
  '93788': 375,
  '93728': 376,
  '93765': 377,
  '93780': 378,
  '74564': 379,
  '74572': 380,
  '93647': 381,
  '51374': 382,
  '51378': 383,
  '93106': 384,
  '48877': 385,
  '49048': 386,
  '92462': 387,
  '91104': 388,
  '56874': 389,
  '56865': 390,
  '57129': 391,
  '57123': 392,
  '48569': 393,
  '49301': 394,
  '49364': 395,
  '49365': 396,
  '49366': 397,
  '49331': 398,
  '49332': 399,
  '49333': 400,
  '49295': 401,
  '49337': 402,
  '49370': 403,
  '49379': 404,
  '49313': 405,
  '73515': 406,
  '73531': 407,
  '73527': 408,
  '73499': 409,
  '73567': 410,
  '74358': 411,
  '74322': 412,
  '74404': 413,
  '74428': 414,
  '73385': 415,
  '73393': 416,
  '74001': 417,
  '74017': 418,
  '58427': 419,
  '58372': 420,
  '56955': 421,
  '56967': 422,
  '56681': 423,
  '48811': 424,
  '93318': 425,
  '58021': 426,
  '58134': 427,
  '93555': 428,
  '93197': 429,
  '57476': 430,
  '57629': 431,
  '57548': 432,
  '57467': 433,
  '46899': 434,
  '46920': 435,
  '46827': 436,
  '46872': 437,
  '46794': 438,
  '46854': 439,
  '46800': 440,
  '87498': 441,
  '88123': 442,
  '88029': 443,
  '87868': 444,
  '87764': 445,
  '87817': 446,
  '87791': 447,
  '97639': 448,
  '107900': 449,
  '107902': 450,
  '107903': 451,
  '107904': 452,
  '108288': 453,
  '108289': 454,
  '108222': 455,
  '107955': 456,
  '108162': 457,
  '107905': 458,
  '108005': 459,
  '107851': 460,
  '107852': 461,
  '107853': 462,
  '107854': 463,
  '107844': 464,
  '107689': 465,
  '107795': 466,
  '107674': 467,
  '107872': 468,
  '90996': 469,
  '55156': 470,
  '55279': 471,
  '94668': 472,
  '66773': 473,
  '56178': 474,
  '56222': 475,
  '73655': 476,
  '90671': 477,
  '49361': 478,
  '49340': 479,
  '49358': 480,
  '55771': 481,
  '90957': 482,
  '88324': 483,
  '55028': 484,
  '49690': 485,
  '49682': 486,
  '49735': 487,
  '49701': 488,
  '49712': 489,
  '59646': 490,
  '59647': 491,
  '59648': 492,
  '59649': 493,
  '59754': 494,
  '59730': 495,
  '59731': 496,
  '59732': 497,
  '59733': 498,
  '59634': 499,
  '59798': 500,
  '93857': 501,
  '72951': 502,
  '73186': 503,
  '73256': 504,
  '73196': 505,
  '71743': 506,
  '71735': 507,
  '71741': 508,
  '71746': 509,
  '71737': 510,
  '75460': 511,
  '75749': 512,
  '75750': 513,
  '75737': 514,
  '75732': 515,
  '89779': 516,
  '77404': 517,
  '71539': 518,
  '91256': 519,
  '89472': 520,
  '75602': 521,
  '75502': 522,
  '91352': 523,
  '77480': 524,
  '72644': 525,
  '76219': 526,
  '71809': 527,
  '71800': 528,
  '71815': 529,
  '71799': 530,
  '75689': 531,
  '71412': 532,
  '89360': 533,
  '71163': 534,
  '90165': 535,
  '75316': 536,
  '71745': 537,
  '59762': 538,
  '59763': 539,
  '59764': 540,
  '59765': 541,
  '59682': 542,
  '85386': 543,
  '53533': 544,
  '54059': 545,
  '54007': 546,
  '54083': 547,
  '54095': 548,
  '57515': 549,
  '57635': 550,
  '57503': 551,
  '57605': 552,
  '46803': 553,
  '46923': 554,
  '46926': 555,
  '46929': 556,
  '47068': 557,
  '47081': 558,
  '47044': 559,
  '57716': 560,
  '57650': 561,
  '58239': 562,
  '57921': 563,
  '57827': 564,
  '58061': 565,
  '58065': 566,
  '47804': 567,
  '47832': 568,
  '47860': 569,
  '47788': 570,
  '57578': 571,
  '46851': 572,
  '46938': 573,
  '46950': 574,
  '46797': 575,
  '46935': 576,
  '46914': 577,
  '46806': 578,
  '47108': 579,
  '57704': 580,
  '57875': 581,
  '47896': 582,
  '47812': 583,
  '47892': 584,
  '47876': 585,
  '47884': 586,
  '47848': 587,
  '47864': 588,
  '58362': 589,
  '48086': 590,
  '58412': 591,
  '58442': 592,
  '49040': 593,
  '48873': 594,
  '49152': 595,
  '49110': 596,
  '49203': 597,
  '49188': 598,
  '50718': 599,
  '50766': 600,
  '50721': 601,
  '50781': 602,
  '50739': 603,
  '57470': 604,
  '57473': 605,
  '46845': 606,
  '46842': 607,
  '46815': 608,
  '57644': 609,
  '57819': 610,
  '58129': 611,
  '57763': 612,
  '57913': 613,
  '57887': 614,
  '48162': 615,
  '48829': 616,
  '56691': 617,
  '48897': 618,
  '49004': 619,
  '56838': 620,
  '56823': 621,
  '56775': 622,
  '56880': 623,
  '56916': 624,
  '56937': 625,
  '57093': 626,
  '57063': 627,
  '51316': 628,
  '51332': 629,
  '51376': 630,
  '51356': 631,
  '51444': 632,
  '51395': 633,
  '51481': 634,
  '51457': 635,
  '51459': 636,
  '97615': 637,
  '97616': 638,
  '97617': 639,
  '97618': 640,
  '97735': 641,
  '97699': 642,
  '97700': 643,
  '97701': 644,
  '97702': 645,
  '97723': 646,
  '97591': 647,
  '108127': 648,
  '108128': 649,
  '107975': 650,
  '108007': 651,
  '108008': 652,
  '108009': 653,
  '107890': 654,
  '107892': 655,
  '46830': 656,
  '46860': 657,
  '46824': 658,
  '50727': 659,
  '51408': 660,
  '97679': 661,
  '97711': 662,
  '97739': 663,
  '97740': 664,
  '97741': 665,
  '97742': 666,
  '97563': 667,
  '97675': 668,
  '97676': 669,
  '97677': 670,
  '97678': 671,
  '97603': 672,
  '97755': 673,
  '97659': 674,
  '107893': 675,
  '107894': 676,
  '108037': 677,
  '108038': 678,
  '107885': 679,
  '107886': 680,
  '108248': 681,
  '108249': 682,
  '107970': 683,
  '107965': 684,
  '108152': 685,
  '108217': 686,
  '108000': 687,
  '107767': 688,
  '107768': 689,
  '107769': 690,
  '107770': 691,
  '107667': 692,
  '107731': 693,
  '55037': 694,
  '55023': 695,
  '55025': 696,
  '55032': 697,
  '55038': 698,
  '55044': 699,
  '55048': 700,
  '55084': 701,
  '55079': 702,
  '55054': 703,
  '55296': 704,
  '55213': 705,
  '55204': 706,
  '55260': 707,
  '55178': 708,
  '97667': 709,
  '55021': 710,
  '55015': 711,
  '55142': 712,
  '55141': 713,
  '55168': 714,
  '59610': 715,
  '59611': 716,
  '59612': 717,
  '59613': 718,
  '55954': 719,
  '56108': 720,
  '56052': 721,
  '56105': 722,
  '56054': 723,
  '56076': 724,
  '56198': 725,
  '55989': 726,
  '56193': 727,
  '56191': 728,
  '56185': 729,
  '56171': 730,
  '56149': 731,
  '56155': 732,
  '56180': 733,
  '56282': 734,
  '56261': 735,
  '56253': 736,
  '56252': 737,
  '58700': 738,
  '58697': 739,
  '58698': 740,
  '58699': 741,
  '58666': 742,
  '108984': 743,
  '58827': 744,
  '90443': 745,
  '54214': 746,
  '60018': 747,
  '60009': 748,
  '59987': 749,
  '59992': 750,
  '89756': 751,
  '89958': 752,
  '54039': 753,
  '90178': 754,
  '53879': 755,
  '71795': 756,
  '54577': 757,
  '54582': 758,
  '54557': 759,
  '54609': 760,
  '54496': 761,
  '54023': 762,
  '54063': 763,
  '54091': 764,
  '54147': 765,
  '54608': 766,
  '54611': 767,
  '54055': 768,
  '54011': 769,
  '54019': 770,
  '85264': 771,
  '85273': 772,
  '84809': 773,
  '85403': 774,
  '85474': 775,
  '85395': 776,
  '53765': 777,
  '86442': 778,
  '53799': 779,
  '58802': 780,
  '53790': 781,
  '53798': 782,
  '53796': 783,
  '49283': 784,
  '49284': 785,
  '49275': 786,
  '85700': 787,
  '84920': 788,
  '84942': 789,
  '84751': 790,
  '85823': 791,
  '85908': 792,
  '61109': 793,
  '87689': 794,
  '85106': 795,
  '88547': 796,
  '87034': 797,
  '54461': 798,
  '49064': 799,
  '56877': 800,
  '56760': 801,
  '56922': 802,
  '56901': 803,
  '56913': 804,
  '56973': 805,
  '86784': 806,
  '88078': 807,
  '89647': 808,
  '97880': 809,
  '97812': 810,
  '97848': 811,
  '97928': 812,
  '80622': 813,
  '80502': 814,
  '80652': 815,
  '80586': 816,
  '80352': 817,
  '80436': 818,
  '80550': 819,
  '49282': 820,
  '49287': 821,
  '58812': 822,
  '60000': 823,
  '88417': 824,
  '97784': 825,
  '97792': 826,
  '97900': 827,
  '97856': 828,
  '97892': 829,
  '71361': 830,
  '86647': 831,
  '49072': 832,
  '49056': 833,
  '56871': 834,
  '56868': 835,
  '57048': 836,
  '57060': 837,
  '56952': 838,
  '91108': 839,
  '86348': 840,
  '53784': 841,
  '87126': 842,
  '87980': 843,
  '88024': 844,
  '87962': 845,
  '86802': 846,
  '57051': 847,
  '57078': 848,
  '56961': 849,
  '48816': 850,
  '48818': 851,
  '52826': 852,
  '60271': 853,
  '55325': 854,
  '55291': 855,
  '55190': 856,
  '55265': 857,
  '57281': 858,
  '66852': 859,
  '66853': 860,
  '66854': 861,
  '66834': 862,
  '66828': 863,
  '66855': 864,
  '66169': 865,
  '86156': 866,
  '93212': 867,
  '93580': 868,
  '57497': 869,
  '57536': 870,
  '57491': 871,
  '57542': 872,
  '46971': 873,
  '46812': 874,
  '58204': 875,
  '58174': 876,
  '58194': 877,
  '57755': 878,
  '93299': 879,
  '93305': 880,
  '93315': 881,
  '93248': 882,
  '93332': 883,
  '93261': 884,
  '93277': 885,
  '73361': 886,
  '73429': 887,
  '73453': 888,
  '55063': 889,
  '55294': 890,
  '84602': 891,
  '51144': 892,
  '47045': 893,
  '50760': 894,
  '50733': 895,
  '73369': 896,
  '74012': 897,
  '74008': 898,
  '51453': 899,
  '51397': 900,
  '71348': 901,
  '85887': 902,
  '86074': 903,
  '48808': 904,
  '56689': 905,
  '54067': 906,
  '88495': 907,
  '71360': 908,
  '61091': 909,
  '93329': 910,
  '93290': 911,
  '93283': 912,
  '93295': 913,
  '93590': 914,
  '49277': 915,
  '49267': 916,
  '93222': 917,
  '57584': 918,
  '57587': 919,
  '57518': 920,
  '57485': 921,
  '46833': 922,
  '55067': 923,
  '73343': 924,
  '73437': 925,
  '73445': 926,
  '73449': 927,
  '58798': 928,
  '58821': 929,
  '49280': 930,
  '54163': 931,
  '54139': 932,
  '53939': 933,
  '53844': 934,
  '90231': 935,
  '90446': 936,
  '60036': 937,
  '48889': 938,
  '48865': 939,
  '48881': 940,
  '49068': 941,
  '85399': 942,
  '53677': 943,
  '86525': 944,
  '49271': 945,
  '49289': 946,
  '49285': 947,
  '85741': 948,
  '85709': 949,
  '85734': 950,
  '85736': 951,
  '85727': 952,
  '85708': 953,
  '85735': 954,
  '84915': 955,
  '84882': 956,
  '85861': 957,
  '85875': 958,
  '85818': 959,
  '85820': 960,
  '86064': 961,
  '86070': 962,
  '86050': 963,
  '86049': 964,
  '86072': 965,
  '85947': 966,
  '61089': 967,
  '61090': 968,
  '61107': 969,
  '88516': 970,
  '87116': 971,
  '54560': 972,
  '51638': 973,
  '90431': 974,
  '90100': 975,
  '54328': 976,
  '89730': 977,
  '53301': 978,
  '66702': 979,
  '66220': 980,
  '66395': 981,
  '97904': 982,
  '97808': 983,
  '97908': 984,
  '97844': 985,
  '97920': 986,
  '97804': 987,
  '52939': 988,
  '66829': 989,
  '66830': 990,
  '51153': 991,
  '66789': 992,
  '51147': 993,
  '62706': 994,
  '84599': 995,
  '84608': 996,
  '84984': 997,
  '84596': 998,
  '51003': 999,
  ...},
 'concepts': {'278': 0,
  '280': 1,
  '279': 2,
  '67': 3,
  '58': 4,
  '277': 5,
  '54': 6,
  '24': 7,
  '51': 8,
  '49': 9,
  '309': 10,
  '85': 11,
  '47': 12,
  '34': 13,
  '81': 14,
  '70': 15,
  '276': 16,
  '61': 17,
  '86': 18,
  '76': 19,
  '77': 20,
  '83': 21,
  '65': 22,
  '50': 23,
  '53': 24,
  '75': 25,
  '310': 26,
  '84': 27,
  '79': 28,
  '80': 29,
  '82': 30,
  '2': 31,
  '63': 32,
  '32': 33,
  '27': 34,
  '110': 35,
  '365': 36,
  '25': 37,
  '46': 38,
  '21': 39,
  '22': 40,
  '292': 41,
  '290': 42,
  '293': 43,
  '1': 44,
  '13': 45,
  '37': 46,
  '48': 47,
  '17': 48,
  '16': 49,
  '4': 50,
  '10': 51,
  '12': 52,
  '15': 53,
  '14': 54,
  '74': 55,
  '92': 56,
  '18': 57,
  '8': 58,
  '105': 59,
  '9': 60,
  '11': 61,
  '311': 62,
  '312': 63,
  '101': 64,
  '94': 65,
  '368': 66,
  '5': 67,
  '375': 68,
  '323': 69,
  '96': 70,
  '322': 71,
  '325': 72,
  '91': 73,
  '35': 74,
  '307': 75,
  '303': 76,
  '308': 77,
  '42': 78,
  '40': 79,
  '296': 80,
  '294': 81,
  '297': 82,
  '39': 83,
  '301': 84,
  '104': 85,
  '64': 86,
  '69': 87,
  '317': 88,
  '299': 89,
  '26': 90,
  '298': 91,
  '173': 92,
  '190': 93,
  '193': 94,
  '221': 95,
  '97': 96,
  '99': 97,
  '321': 98,
  '343': 99,
  '295': 100,
  '43': 101,
  '367': 102,
  '350': 103,
  '346': 104,
  '378': 105,
  '371': 106,
  '340': 107,
  '102': 108,
  '163': 109,
  '204': 110,
  '217': 111,
  '166': 112,
  '203': 113,
  '356': 114,
  '331': 115,
  '334': 116,
  '324': 117,
  '314': 118,
  '362': 119,
  '333': 120,
  '348': 121,
  '165': 122},
 'uid': {'64525': 0,
  '70363': 1,
  '70677': 2,
  '70695': 3,
  '70699': 4,
  '70707': 5,
  '70727': 6,
  '70729': 7,
  '70730': 8,
  '70733': 9,
  '70736': 10,
  '70746': 11,
  '70756': 12,
  '70759': 13,
  '70872': 14,
  '70874': 15,
  '71175': 16,
  '71176': 17,
  '71177': 18,
  '71179': 19,
  '71183': 20,
  '71187': 21,
  '71190': 22,
  '71193': 23,
  '71205': 24,
  '71209': 25,
  '71211': 26,
  '71212': 27,
  '71221': 28,
  '71224': 29,
  '71225': 30,
  '71227': 31,
  '71230': 32,
  '71231': 33,
  '71232': 34,
  '71250': 35,
  '71740': 36,
  '71826': 37,
  '71831': 38,
  '71872': 39,
  '71874': 40,
  '71881': 41,
  '72059': 42,
  '72378': 43,
  '72880': 44,
  '73684': 45,
  '73685': 46,
  '73962': 47,
  '74698': 48,
  '75169': 49,
  '78073': 50,
  '78673': 51,
  '78675': 52,
  '78903': 53,
  '78904': 54,
  '78905': 55,
  '78906': 56,
  '78907': 57,
  '78908': 58,
  '78909': 59,
  '78910': 60,
  '78911': 61,
  '78912': 62,
  '78913': 63,
  '78914': 64,
  '78915': 65,
  '78916': 66,
  '78917': 67,
  '78918': 68,
  '78919': 69,
  '78920': 70,
  '78921': 71,
  '78922': 72,
  '78923': 73,
  '78926': 74,
  '78970': 75,
  '78971': 76,
  '78972': 77,
  '78974': 78,
  '78976': 79,
  '78977': 80,
  '78978': 81,
  '78979': 82,
  '78980': 83,
  '78981': 84,
  '78982': 85,
  '78983': 86,
  '78984': 87,
  '78985': 88,
  '78986': 89,
  '78987': 90,
  '78988': 91,
  '78989': 92,
  '78990': 93,
  '78991': 94,
  '78992': 95,
  '79012': 96,
  '79013': 97,
  '79014': 98,
  '79015': 99,
  '79016': 100,
  '79017': 101,
  '79018': 102,
  '79019': 103,
  '79020': 104,
  '79021': 105,
  '79022': 106,
  '79023': 107,
  '79024': 108,
  '79026': 109,
  '79027': 110,
  '79029': 111,
  '79031': 112,
  '79032': 113,
  '79033': 114,
  '79034': 115,
  '79054': 116,
  '79055': 117,
  '79056': 118,
  '79057': 119,
  '79058': 120,
  '79059': 121,
  '79060': 122,
  '79061': 123,
  '79062': 124,
  '79063': 125,
  '79064': 126,
  '79066': 127,
  '79067': 128,
  '79068': 129,
  '79069': 130,
  '79070': 131,
  '79071': 132,
  '79073': 133,
  '79074': 134,
  '79075': 135,
  '79217': 136,
  '79264': 137,
  '79319': 138,
  '79411': 139,
  '79414': 140,
  '79415': 141,
  '79419': 142,
  '79547': 143,
  '79578': 144,
  '79580': 145,
  '79581': 146,
  '79582': 147,
  '79583': 148,
  '79584': 149,
  '79585': 150,
  '79586': 151,
  '79632': 152,
  '79682': 153,
  '79735': 154,
  '79736': 155,
  '79737': 156,
  '79738': 157,
  '79739': 158,
  '79740': 159,

In [38]:
problem_ids = list(keyid2idx_pb_subset['questions'].keys())
problem_ids_int = [int(x) for x in problem_ids]
print(f'Number of problems in {dataset}: {len(problem_ids_int)}')

Number of problems in assist2009: 17737

In [40]:
subset_df_html_selected = pb_df[pb_df['problem_id'].isin(problem_ids_int)]